### ISSUE TITLE
Multiple Errors

### ISSUE THREAD

**Issue by ZephyrusXI** [Vishnunkumar/clipcrop#3]
First I had cannot import clipcrop from clipcrop
so I changed it to directly call from ClipDrop
Then it started showing another error 
` TypeError: ClipCrop._init_() takes 2 positional arguments but 3 were given`
![WhatsApp Image 2023-08-19 at 15 14 37](https://github.com/Vishnunkumar/clipcrop/assets/111444272/80a67c31-b39b-40dd-98bc-1c78f1ef15bc)
So I put the text in extract image function with only the path in clipcrop function
Then it said `ValueError: Invalid image type. Must be of type PIL.Image.Image, numpy.ndarray, torch.Tensor, tf.Tensor or jax.ndarray.`

I'm yet to find a solution

**Comment by Vishnunkumar** [comment]
Hi,

Thanks for the update, the readme was outdated hence the issue. Please try the newly updated README.MD and revert.

**Comment by ZephyrusXI** [comment]
> Hi,
> 
> Thanks for the update, the readme was outdated hence the issue. Please try the newly updated README.MD and revert.


Also instead of cropping is there a way to mask the things?
Help me out please

**Comment by Vishnunkumar** [comment]
There is a feature to extract out segments from the image using ClipSeg module from the library, but I'm not sure if thats what you are looking for.

**Comment by Vishnunkumar** [comment]
Hi, closing the issue due to inactivity. Please raise a new one if needed
